### ISSUE TITLE
Test Logger Does not Respect LogFilePrefix

### ISSUE THREAD

**Issue by RehanSaeed** [spekt/junit.testlogger#60]
When I run:

> dotnet test --logger:"junit;LogFilePrefix=Foo"

I expect to see a file output with the name: `Foo_net7.0_20221109102716`, instead what I get is `TestResults.xml`

**Comment by Siphonophora** [comment]
Hi,

There are some options to control the log file name, detailed here https://github.com/spekt/testlogger/wiki/Logger-Configuration. 

We don't support `LogFilePrefix`

**Comment by RehanSaeed** [comment]
I'm aware of those options. `LogFilePrefix` is a new feature that was recently added to dotnet test. I thought it would be a good idea for [junit.testlogger](https://github.com/spekt/junit.testlogger) to provide feature parity.

**Comment by Siphonophora** [comment]
Oh, I see. Your original comment read like a bug report to me, not a feature request. 

Current state, supporting the prefix wouldn't be meaningful, because our default file name is static: `TestResults.xml`. So if a user wants any name other than the default, they are supplying the whole file name anyway.  Changing the default would be a breaking change for many users, so its a no-go.

The actual factor stopping the logger from outputting the file name you showed was that we don't offer a timestamp token. Adding the timestamp wouldn't be hard, if it was important.

**Comment by RehanSaeed** [comment]
`LogFilePrefix` as opposed to `LogFileName` is a new setting, so adding support for it wouldn't be a breaking change and would bring it in line with the trx and html loggers.

**Comment by Siphonophora** [comment]
I've been thinking about this and I don't think this makes sense for our loggers. The main reason being we aren't generally trying to follow the trx / html logger conventions.
